### ISSUE TITLE
Non-Linear Toggles for Accordions

### ISSUE THREAD

**Issue by vilav** [vctrfrnndz/jquery-accordion#11]
Hello,

Currently, the Toggle button triggers the accordion that immediately follows that toggle button like:

Toggle
____
Accordion

Is there a way to create a accordion whose trigger is placed somewhere else on the page like so:

Toggle
____
Text, Image
____
Accordion

Thanks
Vilav

**Comment by vctrfrnndz** [comment]
What you're suggesting is totally doable. You just need to configure the the content element by setting the 'contentElement' option.
