### ISSUE TITLE
feature request: 'data-opened' to start opened

### ISSUE THREAD

**Issue by creativeprogramming** [vctrfrnndz/jquery-accordion#12]
Is there an option to start some accordion panel in opened state? 

I tried to achieve this using some:

`  <article data-accordion class="open">`

in the source html  (I'm using singleOpen:false)

But it gives issues if i do that: it's like the height isn't calculated well in this case and i get the accordion trigger title nodes disappearing after their first close event

Do you plan to support some sort of  `data-start-opened` attribute in multi-open mode too?

**Comment by vhugogarcia** [comment]
I would like this option yeah!

**Comment by teodors** [comment]
This is something I would also like to see.

@jeremyraymond I am currently having the same approach, but this is really undesired. Triggering a click will animate opening, but that is something you might not want (definitely not me). Animations take resources and slow down browser.

**Comment by amichel86** [comment]
Thumbs up to add this feature by default :)

**Comment by vctrfrnndz** [comment]
Hey, thanks for the feedback and sorry I am reploying so late. This is actually possible right now if you add the class `open` to your accordion. The plugin will detect it and open that accordion. 

See it here:
http://codepen.io/anon/pen/NRAvOo

I will add this to the readme.

**Comment by amichel86** [comment]
Hey @vctrfrnndz thanks and have a great weekend :D

**Comment by amichel86** [comment]
Hey @vctrfrnndz long time, no see! hehe

I am trying to add the 'open' class via jQuery when clicking another link to target the accordion to open but it doesn't seem to be working. You have any idea why or a workaround for that? Thanks!
