### ISSUE TITLE
Manually recalculate height

### ISSUE THREAD

**Issue by Dobby89** [vctrfrnndz/jquery-accordion#14]
Is there a way to manually recalculate the height of the accordion panel? If you dynamically add an element into the panel, it stays the same height and parts of the elements become obscured.

**Comment by vctrfrnndz** [comment]
Hey, this makes sense. I just added that in https://github.com/vctrfrnndz/jquery-accordion/pull/15. 

You should trigger an 'accordion.refresh' event on your accordion control.

**Comment by Dobby89** [comment]
Thanks, but I'm not sure how to trigger this.

I've tried the following, but it doesn't seem to work.

```
$('.accordion').accordion('accordion.refresh');
```

**Comment by Dobby89** [comment]
@vctrfrnndz Could you help?

**Comment by MamlukiSn** [comment]
@Dobby89 Not sure if this is the right way to go about it but you can replicate the refresh method and call it after dynamically adding the content. I've tried it with a different scenario and it seems to be working okay.
```javascript
 /* get all accordions wrapping the updating sections assuming they could be nested accordions */
var accordions=$('#update-elements-wrapper').parents('[data-accordion]');

/* Loop through accordions updating their heights  */
$(accordions).each( function(i,item){
     if($(item).hasClass('open')){
         var content = $(item).find('> [data-content]'),
         childs = $(content).find('[data-accordion].open > [data-content]'),
         matched = $(content).add(childs);

         calculateHeight(matched);
         $(matched).css('max-height', matched.data('oHeight'));
    }
});

function calculateHeight(el){
        var height = 0;
        $(el).children().each(function(){
        height = height + $(this).outerHeight(true);});
        $(el).data('oHeight', height)
}
```

**Comment by nfriend21** [comment]
I noticed in the code that the refreshHeight function is called when the browser window is resized.  Therefore, the solution that works for me is this:

$(window).trigger('resize');

Call this whenever you need to refresh the height.
