### ISSUE TITLE
Not working when JS is disabled

### ISSUE THREAD

**Issue by abc983ft** [vctrfrnndz/jquery-accordion#23]
When I disable JS, using a chrome extension, the accordion can no longer expand or collapse. Isn’t this supposed to be CSS powered and not rely on JS?

Some people use script blocking extensions on their browser so it would be great if the accordion was still functional(or at least had the nodes auto expanded) when this happens.

**Comment by vctrfrnndz** [comment]
This is a jQuery library that uses CSS transitions.
