### ISSUE TITLE
transitionEasing

### ISSUE THREAD

**Issue by cekvenich** [vctrfrnndz/jquery-accordion#25]
What are other choices other than 'ease' ?

**Comment by blk6r** [comment]
You can use any easing. For example:

```
$('.accordion').accordion({
  transitionSpeed: 1500,
  transitionEasing: 'cubic-bezier(0.000, 1, 1.000, 0)'
});
```

Easing: `linear|ease|ease-in|ease-out|ease-in-out|step-start|step-end|steps(int,start|end)|cubic-bezier(n,n,n,n)|initial|inherit`

If you want to create your proper easing : [https://matthewlein.com/tools/ceaser](https://matthewlein.com/tools/ceaser)
