### ISSUE TITLE
toggling a single accordion causes form to submit.

### ISSUE THREAD

**Issue by tvmaly** [vctrfrnndz/jquery-accordion#8]
Within a signup form, I have the terms of service in an accordion.  When I click on the accordion, it triggers the signup form to be submitted.  The submit button for the form is just below the accordion, but there is ample space so it is not touched.  Have you encountered this before?

**Comment by craigmdennis** [comment]
If you're using a `<button>` as the trigger, make sure it's set to `<button type="button">`

**Comment by vctrfrnndz** [comment]
+1 to @craigmdennis, or use a div as the trigger.
